[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = 
    -v
    --strict-markers
    --tb=short
    --cov=.
    --cov-report=html
    --cov-report=term-missing
    --cov-config=.coveragerc
    --timeout=30
asyncio_mode = auto
qt_api = pyqt5
markers =
    unit: UNIT тесты
    e2e: E2E тесты
    slow: Медленные тесты
    integration: Интеграционные тесты
